

cache:
  paths:
  - node_modules/

services:
  - mysql:5.7

stages:
  - deploy

before_script:
  - node -v
  - npm --version
  - npm install

deploy:
  stage: deploy
  tags:
    - nvm use default
    - node -v
    - npm --version
    - npm install
    - NEST_AUTO_OPS
  script: npm run start:prod
  only:
    - master

# job 1:
#   stage: deploy
#   script: npm run start:prod
#   only:
#     - master

